### ISSUE TITLE
after install, raise error below. it seems no api code

### ISSUE THREAD

**Issue by kylinapp** [jarontai/express-vue-admin#2]
安装时会报错
![default](https://user-images.githubusercontent.com/30215141/30848190-e5857108-a2d0-11e7-9293-8a9ab9520cfc.png)
然后在 ./web/npm run dev 执行会报错
![default](https://user-images.githubusercontent.com/30215141/30848065-6b44c2a4-a2d0-11e7-9969-6dce542fed5d.png)

**Comment by jarontai** [comment]
Sorry for the late reply.

1. The migrate error

It seems like sequelize throws a validate error when you do seed, maybe you should drop and re-create your database, and re-do 'sequelize db:migrate' and 'sequelize db:seed:all'.

The workflow works fine on my machine:
![image](https://user-images.githubusercontent.com/5214514/31976925-fed629b4-b8ff-11e7-8df3-1eb38aa84b51.png)

2. error when do 'npm run dev'

I forgot some steps in readme, please check the updated [readme](https://github.com/jarontai/express-vue-admin#运行).
